apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: llm-compressor-on-push
  namespace: konflux-ai-sig-tenant
  annotations:
    pipelinesascode.tekton.dev/on-event: "[push]"
    pipelinesascode.tekton.dev/on-target-branch: "[main]"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
spec:
  pipelineRef:
    name: llm-compressor-pipeline
  params:
    - name: git-url
      value: "{{ repo_url }}"
    - name: revision
      value: "{{ revision }}"
    - name: output-image
      value: "quay.io/{{ repo_owner }}/{{ repo_name }}:{{ revision }}"
    - name: hermeto-image
      value: "quay.io/rbean/hermeto:x-huggingface"
  workspaces:
    - name: git-basic-auth
      secret:
        secretName: "{{ git_auth_secret }}"
