apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: llm-compressor-pipeline
  labels:
    app.kubernetes.io/version: "1.0"
  annotations:
    description: "Hermetic build pipeline for LLM quantization using llm-compressor"
spec:
  params:
    - name: git-url
      type: string
      description: Source code repository URL
    - name: revision
      type: string
      description: Git revision to checkout
      default: main
    - name: output-image
      type: string
      description: Target image reference for OCI artifacts
      default: ""
    - name: image-expires-after
      type: string
      description: Image expiration time
      default: "5d"

  workspaces:
    - name: git-basic-auth
      description: Git credentials (optional)
      optional: true

  results:
    - name: IMAGE_URL
      description: Repository where the compressed model artifact was pushed
      value: $(tasks.llm-compressor.results.IMAGE_URL)
    - name: IMAGE_DIGEST
      description: Digest of the compressed model artifact just pushed
      value: $(tasks.llm-compressor.results.IMAGE_DIGEST)
    - name: CHAINS-GIT_URL
      description: The precise URL that was fetched by the clone task
      value: $(tasks.clone-repository.results.url)
    - name: CHAINS-GIT_COMMIT
      description: The precise commit SHA that was fetched by the clone task
      value: $(tasks.clone-repository.results.commit)

  tasks:
    # Task 1: Initialize with OCI-TA
    - name: init
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:3ca52e1d8885fc229bd9067275f44d5b21a9a609981d0324b525ddeca909bf10
          - name: name
            value: init
          - name: kind
            value: task
      params:
        - name: image-url
          value: "$(params.output-image)"

    # Task 2: Clone repository using OCI-TA
    - name: clone-repository
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-git-clone-oci-ta:0.1@sha256:bb2f8f1edec47faa08c1929f2ffc6748f3a96af9644e6c40000081c6ff3ec894
          - name: name
            value: git-clone-oci-ta
          - name: kind
            value: task
      params:
        - name: url
          value: "$(params.git-url)"
        - name: revision
          value: "$(params.revision)"
        - name: ociStorage
          value: "$(params.output-image).git"
        - name: ociArtifactExpiresAfter
          value: "$(params.image-expires-after)"
      workspaces:
        - name: basic-auth
          workspace: git-basic-auth
      runAfter:
        - init

    # Task 3: Prefetch dependencies using hermeto x-huggingface with OCI-TA
    - name: prefetch-dependencies
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/ralphbean/build-definitions
          - name: revision
            value: x-huggingface
          - name: pathInRepo
            value: task/prefetch-dependencies-oci-ta/0.2/prefetch-dependencies-oci-ta.yaml
      params:
        - name: input
          # https://github.com/hermetoproject/hermeto/pull/1141
          # https://youtu.be/fY4tXDkUa5I
          value: "x-huggingface"
        - name: SOURCE_ARTIFACT
          value: "$(tasks.clone-repository.results.SOURCE_ARTIFACT)"
        - name: ociStorage
          value: "$(params.output-image)"
        - name: ociArtifactExpiresAfter
          value: "$(params.image-expires-after)"
      runAfter:
        - clone-repository

    # Task 4: Run LLM compressor quantization with GPU on remote host
    - name: llm-compressor
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/ralphbean/build-definitions
          - name: revision
            value: llm-compressor
          - name: pathInRepo
            value: task/llm-compressor-remote-oci-ta/0.1/llm-compressor-remote-oci-ta.yaml
      params:
        - name: SOURCE_ARTIFACT
          value: "$(tasks.clone-repository.results.SOURCE_ARTIFACT)"
        - name: CACHI2_ARTIFACT
          value: "$(tasks.prefetch-dependencies.results.CACHI2_ARTIFACT)"
        - name: IMAGE
          value: "$(params.output-image)"
        - name: COMPRESSOR_IMAGE
          value: "quay.io/rbean/llm-compressor:pr-1902"
        - name: SCRIPT
          value: "compress.py"
        - name: PLATFORM
          value: "linux-g64xlarge/amd64"
        - name: GIT_URL
          value: "$(params.git-url)"
        - name: GIT_COMMIT
          value: "$(params.revision)"
        - name: BUILDAH_DEVICES
          value:
            - "/dev/nvidia0"
        - name: SCRIPT_ARGS
          value:
            - "--output-dir"
            - "/var/workdir/output"
      runAfter:
        - prefetch-dependencies
