apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: llm-compressor-pipeline
  labels:
    app.kubernetes.io/version: "1.0"
  annotations:
    description: "Hermetic build pipeline for LLM quantization using llm-compressor"
spec:
  params:
    - name: git-url
      type: string
      description: Source code repository URL
    - name: revision
      type: string
      description: Git revision to checkout
      default: main
    - name: output-image
      type: string
      description: Target image reference for OCI artifacts
      default: ""
    - name: image-expires-after
      type: string
      description: Image expiration time
      default: "5d"

  workspaces:
    - name: git-basic-auth
      description: Git credentials (optional)
      optional: true

  tasks:
    # Task 1: Initialize with OCI-TA
    - name: init
      taskRef:
        resolver: bundles
        params:
          - name: bundle
            value: quay.io/konflux-ci/tekton-catalog/task-init:0.2@sha256:bbf313b09740fb39b3343bc69ee94b2a2c21d16a9304f9b7c111c305558fc346
          - name: name
            value: init
          - name: kind
            value: task
      params:
        - name: image-url
          value: "$(params.output-image)"

    # Task 4: Run LLM compressor quantization with GPU on remote host
    - name: llm-compressor
      taskRef:
        resolver: git
        params:
          - name: url
            value: https://github.com/ralphbean/build-definitions
          - name: revision
            value: llm-compressor
          - name: pathInRepo
            value: task/llm-compressor-remote-oci-ta/0.1/llm-compressor-remote-oci-ta.yaml
      params:
        - name: SOURCE_ARTIFACT
          value: "oci:quay.io/redhat-user-workloads/konflux-ai-sig-tenant/llm-compressor-demo@sha256:1fe63a2d3aa980c4296dfa85fbdecc1bc479bd00e68362d70c809c11b6cf5d4d"
        - name: CACHI2_ARTIFACT
          value: "oci:quay.io/redhat-user-workloads/konflux-ai-sig-tenant/llm-compressor-demo@sha256:3a9db4a54f76cb2b1dc314301da9841f72889067306c9f16316e82292e328db4"
        - name: IMAGE
          value: "$(params.output-image)"
        - name: COMPRESSOR_IMAGE
          value: "registry.redhat.io/rhaiis/model-opt-cuda-rhel9:3.2.3-1760571858"
        - name: SCRIPT
          value: "compress.py"
        - name: PLATFORM
          value: "linux/g64xlarge-amd64"
        - name: BUILDAH_DEVICES
          value:
            - "nvidia.com/gpu=all"
      runAfter:
        - init
